### ISSUE TITLE
Blueprint breaks on creation if there is space in name

### ISSUE THREAD

**Issue by IoIoToTM** [LoGaCulture/LUTE#23]
When I tried to make a very simple blueprint, I put a space in the name, and this then breaks the program with an error.

![image](https://github.com/LoGaCulture/LUTE/assets/6618932/720b6c9b-d061-4df6-bc44-c15ac1b6440d)

![image](https://github.com/LoGaCulture/LUTE/assets/6618932/84a07cab-d616-45b6-8e8a-cb20ccb40dd6)

And this is the generated code:

```
using System.Linq;
using UnityEditor;
using UnityEngine;

public class CustomBlueprintMenu
{
[MenuItem("LUTE/Create/Blueprints/Simple_Choice_and_Converge", false, 100)]
static void AddBlueprint_Simple_Choice_and_Converge()
{
    EngineMenuItems.AddBlueprint("Simple_Choice_and_Converge");
}
[MenuItem("LUTE/Create/Blueprints/Blueprint test", false, 100)]
static void AddBlueprint_Blueprint test()
{
    EngineMenuItems.AddBlueprint("Blueprint test");
}
}

```

I looked at the code when creating the Blueprint, and a very simple fix would be either just saying "No Spaces Allowed", or just stripping any spaces (or even special characters) before the function is called:
```
GraphWindow.cs: 621

        // Add a button to the blueprint window to create a blueprint with the given name
        if (GUI.Button(buttonRect, "Create Blueprint"))
        {
            if (!string.IsNullOrEmpty(blueprintName))
            {
                //strip any spaces from the blueprint name
                blueprintName = blueprintName.Replace(" ", "");
                CreateBlueprint(blueprintName);
            }
        }
```

**Comment by Jacki3** [comment]
Have updated the code to replace the empty spaces in the name with underscores and will update documentation to reflect that Blueprint names should use CamelCase rather than empty spaces (or hyphen/underscores if chosen). 

Closing this as resolved as the fix @IoIoToTM has mentioned works.
