### ISSUE TITLE
Hide locations

### ISSUE THREAD

**Issue by IoIoToTM** [LoGaCulture/LUTE#24]
When creating a simple game where I want to have a hidden location that can be unlocked afterwards, there is no way for me to hide it from the map view. This can add a lot of diversity to the games. Maybe it could be a simple checkbox in the Variables menu for every Location Variable (this is a quick mock-up to show):

![image](https://github.com/LoGaCulture/LUTE/assets/6618932/85cd377d-be23-4bc9-ba6c-06ca9926cfab)

**Comment by Jacki3** [comment]
The simplest implementation currently will be to have a 'Hide Location' Order which will hide the chosen location from the map. This can then be reversed to 'Show Location' Order which can be called when certain criteria are met. This will essentially add a boolean to the Location Variable (show/hide the visuals) which we could then make public in the variable inspector if this is desired.

**Comment by Jacki3** [comment]
Added Orders to Reveal/Hide Location

Added two orders that allow users to hide or reveal location markers ('hide/reveal location')

Fixed the spawn on map class as it was duplicating locations found

Two new orders to help users who want to hide/reveal multiple locations using an array of locations

Have been tested but could do with some UX and bug testing

If the poster is happy with this implementation then I will close this but will keep it open for now until we all reach an agreement and this has been tested.

**Comment by Jacki3** [comment]
Besides from more in-depth testing, this issue is considered resolved and will be merged into main/based into a new release.
